services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SCHEDULER=1
      - SCHEDULER_RUN_ON_BOOT=1
      - PYTHONUNBUFFERED=1
      - GUNICORN_CMD_ARGS=--log-level=info
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db_data:
