services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SCHEDULER=1
      - SCHEDULER_RUN_ON_BOOT=1
      - PYTHONUNBUFFERED=1
      - GUNICORN_CMD_ARGS=--log-level=info
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine   # lightweight redis image       # expose if you want to debug from host
    volumes:
      - redis_data:/data    # optional persistence

volumes:
  db_data:
  redis_data:
