"""variable

Revision ID: 0b99b4e5b672
Revises: 830519c486d4
Create Date: 2025-08-12 13:11:03.152031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b99b4e5b672'
down_revision = '830519c486d4'
branch_labels = None
depends_on = None


from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the ENUM types first.
    op.execute("CREATE TYPE category AS ENUM ('science', 'history', 'sport', 'geography', 'art')")
    op.execute("CREATE TYPE difficulty AS ENUM ('easy', 'medium', 'hard')")

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        # Alter the existing 'category' column to use the new ENUM type
        batch_op.alter_column('category', 
                              existing_type=sa.VARCHAR(length=255),
                              type_=sa.Enum('science', 'history', 'sport', 'geography', 'art', name='category'),
                              server_default='science',
                              existing_nullable=False,
                              postgresql_using="category::category")
        
        # Add the new 'difficulty' column
        batch_op.add_column(sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), server_default='easy', nullable=False))
        
        # Create indexes
        batch_op.create_index(batch_op.f('ix_quiz_questions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_questions_difficulty'), ['difficulty'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_difficulty'))
        batch_op.drop_index(batch_op.f('ix_quiz_questions_category'))
        batch_op.drop_column('difficulty')
        
        # Alter 'category' back to its original String type
        batch_op.alter_column('category', 
                              existing_type=sa.Enum('science', 'history', 'sport', 'geography', 'art', name='category'),
                              type_=sa.VARCHAR(length=255),
                              server_default=None,
                              existing_nullable=False)

    # Drop the ENUM types
    op.execute("DROP TYPE difficulty")
    op.execute("DROP TYPE category")
    # ### end Alembic commands ###