"""roles

Revision ID: 830519c486d4
Revises: ab877ba6ecc1
Create Date: 2025-08-12 08:35:22.093156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830519c486d4'
down_revision = 'ab877ba6ecc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='user', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
