"""add

Revision ID: ab877ba6ecc1
Revises: 5322f362b27d
Create Date: 2025-08-11 13:33:01.886757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab877ba6ecc1'
down_revision = '5322f362b27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('opens_at < closes_at', name='ck_quiz_time_window'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizzes_closes_at'), ['closes_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_opens_at'), ['opens_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_week_start_date'), ['week_start_date'], unique=True)

    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'order', name='uq_question_order_per_quiz')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('quiz_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'user_id', name='uq_one_submission_per_quiz')
    )
    with op.batch_alter_table('quiz_submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_submission_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_submission_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_submission_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_options_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('points')

    with op.batch_alter_table('quiz_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_options_question_id'))

    op.drop_table('quiz_options')
    with op.batch_alter_table('quiz_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_submission_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_submission_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_quiz_submission_quiz_id'))

    op.drop_table('quiz_submission')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_quiz_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_week_start_date'))
        batch_op.drop_index(batch_op.f('ix_quizzes_opens_at'))
        batch_op.drop_index(batch_op.f('ix_quizzes_closes_at'))

    op.drop_table('quizzes')
    # ### end Alembic commands ###
